football_teams = [
    "Real Madrid",
    "Barcelona",
    "Manchester United",
    "Liverpool",
    "Bayern Munich",
    "Juventus",
    "Paris Saint-Germain",
    "Manchester City",
    "Chelsea",
    "Arsenal",
    "AC Milan",
    "Inter Milan",
    "Atletico Madrid",
    "Tottenham Hotspur",
    "Borussia Dortmund",
    "Ajax",
    "Bayer Leverkusen",
    "AS Roma",
    "Napoli",
    "Valencia",
    "Sevilla",
    "Everton",
    "Leicester City",
    "Lyon",
    "Villarreal",
    "Roma",
    "Shakhtar Donetsk",
    "Celtic",
    "Zenit St. Petersburg",
    "Porto",
    "Benfica",
    "Galatasaray",
    "Fenerbahçe",
    "PSV Eindhoven",
    "Olympique Marseille",
    "Schalke 04",
    "Wolverhampton Wanderers",
    "Southampton",
    "Crystal Palace",
    "Newcastle United",
    "Real Betis",
    "Athletic Bilbao",
    "Werder Bremen",
    "Valencia CF",
    "Lazio",
    "Burnley",
    "Sampdoria",
    "Monaco",
    "Boca Juniors",
    "River Plate",
]
